function x = vectorToStateTRO(xk)
    x = StateTRO(xk(1), ...
              xk(2), ...
              xk(3), ...
              xk(4), ...
              xk(5), ...
              xk(6), ...
              xk(7), ...
              xk(8), ...
              xk(9));
end