function config = configTRO()
    config.solver = 'acados'; % ipopt, acados
    config.NX = 8;
    config.NU  = 4;
    
    config.NB = 8;  % max number of bounds
    config.NS = 7; % number of soft constraints

    config.N = 1236; % horizon length
    config.NSpline = 5000; % number of track approximation points

    config.siIndex = struct('n',1, ...
                     'miu',2, ...
                     'vx',3, ...
                     'vy',4, ...
                     'r',5, ...
                     'throttle',6, ...
                     'steeringAngle',7, ...
                     'brakes',8, ...
                     'dThrottle',1, ...
                     'dSteeringAngle',2, ...
                     'dBrakes',3, ...
                     'Mtv',4);

end

